version: 2.1

executors:
  android:
    docker:
      - image: circleci/android:api-30
    environment:
      JAVA_HOME: /opt/android/sdk
      ANDROID_HOME: /opt/android/sdk

  ios:
    macos:
      xcode: "15.4.0"

jobs:
  build-jvm:
    docker:
      - image: circleci/openjdk:17-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
            - gradle-cache-
      - run: ./gradlew jvmTest
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}

  build-android:
    executor: android
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
            - gradle-cache-
      - run:
          name: Accept SDK Licenses
          command: yes | sdkmanager --licenses
      - run: ./gradlew androidTest
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}

  build-ios:
    macos:
      xcode: "15.4.0"
    steps:
      - checkout
      - run:
          name: Set up CocoaPods
          command: pod install --repo-update
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}
            - gradle-cache-
      - run: ./gradlew iosTest
      - save_cache:
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          key: gradle-cache-{{ checksum "build.gradle.kts" }}-{{ checksum "settings.gradle.kts" }}

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-jvm
      - build-android
      - build-ios
