version: 2.1

orbs:
  android: circleci/android@1.0.3
  macos: circleci/macos@2.1.0

jobs:
  build-android:
    docker:
      - image: circleci/android:2022.04.1
    environment:
      JAVA_HOME: /usr/local/openjdk-17
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup Java 17
          command: |
            sudo apt-get update
            sudo apt-get install openjdk-17-jdk
            java -version
      - run:
          name: Build Android app and run tests
          command: ./gradlew clean assembleDebug build test --parallel

  build-ios:
    macos:
      xcode: "14.0.0"
    steps:
      - checkout
      - run:
          name: Setup Java 17
          command: |
            brew install --cask adoptopenjdk/openjdk/adoptopenjdk17
            java -version
      - run:
          name: Build with Xcode
          command: xcodebuild -workspace ios-app/alkaa.xcodeproj/project.xcworkspace -configuration Debug -scheme alkaa -sdk iphonesimulator

workflows:
  version: 2
  build:
    jobs:
      - build-android
      - build-ios
